vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        video_download:
            upload_destination: download.storage
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
        video_cover:
            upload_destination: video_cover.storage
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
